services:
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "3000:5001"

  frontend:
    build: ./Frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001
    ports:
      - "5173:5173"